import { Injectable, NotFoundException } from '@nestjs/common';

import {
  CreateInvitationServiceInput,
  GetInvitationServiceInput,
  GetInvitationsServiceInput,
  UpdateInvitationServiceInput,
} from '@/modules/invitation/defs/invitation-service.defs';
import { InvitationEntity } from '@/modules/invitation/entity/invitation.entity';
import { InvitationRepository } from '@/modules/invitation/repository/invitation.repository';
import { HallService } from '@/modules/hall/hall.service';
import { InvitationRecipientService } from '@/modules/invitation-recipient/invitation-recipient.service';
import { HallEntity } from '@/modules/hall/entity/hall.entity';

@Injectable()
export class InvitationService {
  constructor(
    private readonly invitationRepository: InvitationRepository,
    private readonly hallService: HallService,
    private readonly invitationRecipientService: InvitationRecipientService,
  ) {}

  async createInvitation(input: CreateInvitationServiceInput): Promise<InvitationEntity> {
    return await this.invitationRepository.create({
      title: input.title,
      description: input.description,
      eventDate: input.eventDate,
      maxGuestsAllowed: input.maxGuestsAllowed,
      hallId: input.hallId,
      creatorId: input.creatorId,
    });
  }

  async getInvitationById(input: GetInvitationServiceInput): Promise<InvitationEntity> {
    const invitation = await this.invitationRepository.getById({
      id: input.id,
      includeCreator: input.includeCreator,
      includeMessages: input.includeMessages,
      includeRecipients: input.includeRecipients,
    });

    if (!invitation) {
      throw new NotFoundException(`Invitation with ID ${input.id} not found`);
    }

    // Check if the invitation belongs to the user's hall
    if (input.userHallId && invitation.hallId !== input.userHallId) {
      throw new NotFoundException(`Invitation with ID ${input.id} not found`);
    }

    return invitation;
  }

  async getInvitations(input: GetInvitationsServiceInput): Promise<InvitationEntity[]> {
    return await this.invitationRepository.getAll({
      hallId: input.hallId,
      creatorId: input.creatorId,
      includeCreator: input.includeCreator,
      includeMessages: input.includeMessages,
      includeRecipients: input.includeRecipients,
      limit: input.limit || 20,
      offset: input.offset || 0,
    });
  }

  async updateInvitation(input: UpdateInvitationServiceInput): Promise<InvitationEntity> {
    // First check if invitation exists and belongs to user's hall
    await this.getInvitationById({
      id: input.id,
      userHallId: input.userHallId,
    });

    return await this.invitationRepository.update({
      id: input.id,
      title: input.title,
      description: input.description,
      eventDate: input.eventDate,
    });
  }

  async deleteInvitation(id: number, userHallId?: number): Promise<void> {
    // First check if invitation exists and belongs to user's hall
    await this.getInvitationById({ id, userHallId });

    await this.invitationRepository.delete(id);
  }

  async generateQRCode(input: {
    invitationId: number;
    hallId: number;
    grantedBy: number;
    expiresInDays?: number;
  }): Promise<{
    qrData: any;
    expiresAt: Date;
  }> {
    // First verify invitation exists and belongs to the hall
    await this.getInvitationById({
      id: input.invitationId,
      userHallId: input.hallId,
    });

    // Generate QR code data using MobileTokenService
    // Note: We would need to inject MobileTokenService here
    // For now, keeping the placeholder structure
    const expiresAt = new Date();
    expiresAt.setDate(expiresAt.getDate() + (input.expiresInDays || 30));

    return {
      qrData: {
        invitationId: input.invitationId,
        accessToken: 'placeholder_token', // Would be generated by MobileTokenService
        appUrl: process.env.MOBILE_APP_URL || 'https://app.yourplatform.com/invitation/access',
      },
      expiresAt,
    };
  }

  async getInvitationDetails(invitationId: number): Promise<{
    invitation: InvitationEntity;
    hall: HallEntity;
    submittedGuestsCount: number;
  }> {
    // Get invitation with hall details
    const invitation = await this.getInvitationById({
      id: invitationId,
      includeCreator: false,
      includeMessages: false,
      includeRecipients: false,
    });

    if (!invitation) {
      throw new NotFoundException('Invitation not found');
    }

    // Get hall details using our new findHallById method
    const hall = await this.hallService.findHallById(invitation.hallId);

    if (!hall) {
      throw new NotFoundException('Hall not found');
    }

    // Get current submission count
    const submittedGuestsCount =
      await this.invitationRecipientService.getSubmittedGuestsCount(invitationId);

    return {
      invitation,
      hall,
      submittedGuestsCount,
    };
  }

  canStillSubmitGuests(invitation: InvitationEntity): boolean {
    const now = new Date();
    return now < invitation.submissionDeadline;
  }
}
